#ifndef BROWSERPROJECT_MAIN_BROWSER_H
#define BROWSERPROJECT_MAIN_BROWSER_H

#include "Tab.h"
#include "Node.h"
#include "LinkedList.h"
#include "Window.h"
#include "Browser.h"

int main()
{
    Browser* brows = new Browser();
    Window a;
    Window b;
    Window c;
    Window d;
    Tab A = Tab("ccc", "ss", "p");
    Tab B = Tab("bbb", "r", "x");
    Tab C = Tab("pp", "ss", "ppp");
    Tab D = Tab("s", "fff", "ss");
    Tab E = Tab("y", "g", "nnn");
    Tab F = Tab("hhh", "d", "o");
    Tab G = Tab("y", "j", "bb");
    Tab H = Tab("kk", "ll", "j");
    Tab I = Tab("ddd", "aa", "nnn");
    Tab J = Tab("ppp", "g", "t");
    Tab K = Tab("rrr", "s", "b");
    Tab L = Tab("iii", "r", "lll");
    Tab M = Tab("rrr", "x", "qq");
    Tab N = Tab("s", "ppp", "pp");
    Tab O = Tab("v", "mm", "m");
    Tab P = Tab("uuu", "yy", "www");
    Tab Q = Tab("nnn", "jj", "ppp");
    Tab R = Tab("ccc", "sss", "hh");
    Tab S = Tab("bb", "oo", "r");
    Tab T = Tab("t", "vv", "b");
    Tab U = Tab("uuu", "c", "nn");
    Tab V = Tab("tt", "nn", "mm");
    Tab W = Tab("ll", "nnn", "ccc");
    Tab X = Tab("q", "q", "n");
    Tab Y = Tab("tt", "zz", "zzz");
    Tab Z = Tab("eee", "qq", "rr");
    a.newTab(A);
    b.moveActiveTabTo(3);
    c.newTab(B);
    d.changeActiveTabTo(3);
    a.moveActiveTabTo(4);
    b.changeActiveTabTo(4);
    c.newTab(C);
    d.moveActiveTabTo(4);
    a.newTab(D);
    b.moveActiveTabTo(1);
    c.moveActiveTabTo(1);
    d.moveActiveTabTo(1);
    a.moveActiveTabTo(4);
    b.moveActiveTabTo(4);
    c.newTab(E);
    d.newTab(F);
    a.changeActiveTabTo(5);
    b.newTab(G);
    c.newTab(H);
    d.moveActiveTabTo(5);
    a.moveActiveTabTo(5);
    b.moveActiveTabTo(5);
    c.moveActiveTabTo(5);
    d.newTab(I);
    a.changeActiveTabTo(4);
    b.moveActiveTabTo(4);
    c.newTab(J);
    d.newTab(K);
    a.moveActiveTabTo(0);
    b.newTab(L);
    c.moveActiveTabTo(0);
    d.newTab(M);
    a.newTab(N);
    b.moveActiveTabTo(4);
    c.changeActiveTabTo(4);
    d.changeActiveTabTo(4);
    a.moveActiveTabTo(4);
    b.changeActiveTabTo(4);
    c.newTab(O);
    d.newTab(P);
    a.moveActiveTabTo(2);
    b.moveActiveTabTo(2);
    c.newTab(Q);
    d.moveActiveTabTo(2);
    a.moveActiveTabTo(2);
    b.moveActiveTabTo(2);
    c.newTab(R);
    d.changeActiveTabTo(2);
    a.newTab(S);
    b.moveActiveTabTo(3);
    c.moveActiveTabTo(3);
    d.newTab(T);
    a.moveActiveTabTo(3);
    b.newTab(U);
    c.changeActiveTabTo(3);
    d.changeActiveTabTo(3);
    a.changeActiveTabTo(0);
    b.changeActiveTabTo(0);
    c.newTab(V);
    d.newTab(W);
    a.newTab(X);
    b.changeActiveTabTo(4);
    c.changeActiveTabTo(4);
    d.newTab(Y);
    a.newTab(Z);
    b.moveActiveTabTo(1);
    c.changeActiveTabTo(1);
    d.newTab(Z);
    a.changeActiveTabTo(0);
    b.changeActiveTabTo(0);
    d.moveActiveTabTo(0);
    a.moveActiveTabTo(4);
    b.changeActiveTabTo(4);
    c.moveActiveTabTo(4);
    b.moveActiveTabTo(0);
    c.changeActiveTabTo(0);
    b.moveActiveTabTo(1);
    d.moveActiveTabTo(1);
    a.moveActiveTabTo(1);
    b.changeActiveTabTo(1);
    c.moveActiveTabTo(1);
    d.changeActiveTabTo(1);
    b.changeActiveTabTo(3);
    d.changeActiveTabTo(3);
    a.moveActiveTabTo(0);
    b.changeActiveTabTo(0);
    c.changeActiveTabTo(0);
    a.changeActiveTabTo(1);
    d.moveActiveTabTo(5);
    a.changeActiveTabTo(3);
    c.moveActiveTabTo(3);
    d.moveActiveTabTo(3);
    b.moveActiveTabTo(2);
    c.changeActiveTabTo(2);
    d.changeActiveTabTo(2);
    b.changeActiveTabTo(2);
    c.changeActiveTabTo(2);
    d.changeActiveTabTo(2);
    a.moveActiveTabTo(4);
    b.moveActiveTabTo(4);
    c.changeActiveTabTo(4);
    a.moveActiveTabTo(1);
    c.moveActiveTabTo(1);
    d.moveActiveTabTo(1);
    a.moveActiveTabTo(3);
    b.moveActiveTabTo(3);
    c.changeActiveTabTo(3);
    d.changeActiveTabTo(3);
    a.changeActiveTabTo(1);
    b.changeActiveTabTo(1);
    c.moveActiveTabTo(1);
    b.moveActiveTabTo(4);
    c.changeActiveTabTo(4);
    a.changeActiveTabTo(3);
    c.changeActiveTabTo(3);
    d.changeActiveTabTo(3);
    a.changeActiveTabTo(0);
    b.changeActiveTabTo(0);
    a.changeActiveTabTo(4);
    b.moveActiveTabTo(4);
    c.moveActiveTabTo(4);
    a.moveActiveTabTo(3);
    b.changeActiveTabTo(3);
    c.changeActiveTabTo(3);
    d.moveActiveTabTo(3);
    a.changeActiveTabTo(4);
    c.moveActiveTabTo(4);
    d.moveActiveTabTo(4);
    a.changeActiveTabTo(2);
    b.moveActiveTabTo(2);
    c.changeActiveTabTo(2);
    d.changeActiveTabTo(2);
    a.moveActiveTabTo(5);
    b.moveActiveTabTo(5);
    c.changeActiveTabTo(4);
    d.changeActiveTabTo(4);
    a.moveActiveTabTo(0);
    b.moveActiveTabTo(0);
    c.changeActiveTabTo(0);
    a.moveActiveTabTo(0);
    b.moveActiveTabTo(0);
    c.moveActiveTabTo(0);
    d.changeActiveTabTo(0);
    a.changeActiveTabTo(2);
    b.moveActiveTabTo(2);
    c.moveActiveTabTo(2);
    d.moveActiveTabTo(2);
    a.moveActiveTabTo(0);
    b.moveActiveTabTo(0);
    c.changeActiveTabTo(0);
    d.moveActiveTabTo(0);
    a.changeActiveTabTo(2);
    b.moveActiveTabTo(2);
    d.changeActiveTabTo(2);
    a.moveActiveTabTo(1);
    b.changeActiveTabTo(1);
    c.changeActiveTabTo(1);
    a.moveActiveTabTo(3);
    b.moveActiveTabTo(3);
    c.moveActiveTabTo(3);
    d.changeActiveTabTo(3);
    b.moveActiveTabTo(4);
    c.moveActiveTabTo(4);
    d.changeActiveTabTo(4);
    brows->addWindow(a);
    brows->addWindow(b);
    brows->addWindow(c);
    brows->addWindow(d);
    brows->mergeAllWindows();
    brows->closeWindow();
    brows->getWindow(0);
    brows->print();
    brows->newWindow();
    brows->getWindow(7);
    brows->print();
    brows->getWindow(4);
    brows->closeWindow();
    brows->mergeAllWindows();
    brows->print();
    brows->closeEmptyWindows();
    brows->newWindow();
    brows->print();
    brows->switchToWindow(6);
    brows->print();
    brows->print();
    brows->getWindow(3);
    brows->print();
    brows->switchToWindow(1);
    brows->newWindow();
    brows->closeWindow();
    brows->newWindow();
    brows->closeWindow();
    brows->closeEmptyWindows();
    brows->mergeAllWindows();
    brows->newWindow();
    brows->closeEmptyWindows();
    brows->print();
    brows->switchToWindow(3);
    brows->closeWindow();
    brows->mergeAllWindows();
    brows->print();
    brows->closeEmptyWindows();
    brows->print();
    brows->closeEmptyWindows();
    brows->newWindow();
    brows->getWindow(6);
    brows->closeWindow();
    brows->switchToWindow(5);
    brows->closeWindow();
    brows->switchToWindow(4);
    brows->switchToWindow(3);
    brows->newWindow();
    brows->switchToWindow(2);
    brows->print();
    brows->newWindow();
    brows->mergeAllWindows();
    brows->getWindow(7);
    brows->switchToWindow(2);
    brows->closeEmptyWindows();
    brows->closeWindow();
    brows->closeEmptyWindows();
    brows->mergeAllWindows();
    brows->closeEmptyWindows();
    brows->getWindow(5);
    brows->mergeAllWindows();
    brows->mergeAllWindows();
    brows->closeEmptyWindows();
    brows->getWindow(3);
    brows->getWindow(6);
    brows->getWindow(5);
    brows->print();
    brows->closeWindow();
    brows->newWindow();
    brows->switchToWindow(5);
    brows->switchToWindow(7);
    brows->getWindow(2);
    brows->mergeAllWindows();
    brows->print();
    brows->print();
    brows->switchToWindow(8);
    brows->print();
    brows->closeWindow();
    brows->print();
    brows->print();
    brows->closeWindow();
    brows->newWindow();
    brows->mergeAllWindows();
    brows->newWindow();
    brows->getWindow(1);
    brows->print();
    brows->newWindow();
    brows->mergeAllWindows();
    brows->mergeAllWindows();
    brows->newWindow();
    brows->switchToWindow(4);
    brows->print();
    brows->switchToWindow(5);
    brows->switchToWindow(3);
    brows->closeEmptyWindows();
    brows->mergeAllWindows();
    brows->closeEmptyWindows();
    brows->mergeAllWindows();
    brows->getWindow(3);
    brows->closeEmptyWindows();
    brows->newWindow();
    brows->print();
    brows->closeEmptyWindows();
    brows->getWindow(0);
    brows->switchToWindow(8);
    brows->closeWindow();
    brows->getWindow(6);
    brows->closeEmptyWindows();
    brows->newWindow();
    brows->mergeAllWindows();
    brows->mergeAllWindows();
    brows->switchToWindow(0);
    brows->closeWindow();
    brows->newWindow();
    brows->closeEmptyWindows();
    brows->print();
    brows->mergeAllWindows();
    brows->print();
    brows->newWindow();
    brows->switchToWindow(6);
    brows->closeWindow();
    brows->closeWindow();

    /*Window window1;
    Window window2;
    Window window3;
    Browser my_browser;

    my_browser.print();
    my_browser.newWindow();
    my_browser.newWindow();
    my_browser.print();

    Node<Tab> new_tab1 = Tab("002", "001", "003");
    Node<Tab> new_tab2 = Tab("020", "010", "030");
    Node<Tab> new_tab3 = Tab("022", "011", "033");

    my_browser.getWindow(0).newTab(new_tab1.data);
    my_browser.getWindow(0).newTab(new_tab2.data);
    my_browser.getWindow(0).newTab(new_tab3.data);

    Node<Tab> new_tab4 = Tab("202", "101", "303");
    Node<Tab> new_tab5 = Tab("220", "110", "330");
    Node<Tab> new_tab6 = Tab("222", "111", "333");
    Node<Tab> new_tab7 = Tab("200", "100", "300");

    my_browser.getWindow(1).newTab(new_tab4.data);
    my_browser.getWindow(1).newTab(new_tab5.data);
    my_browser.getWindow(1).newTab(new_tab6.data);
    my_browser.getWindow(1).newTab(new_tab7.data);

    my_browser.getWindow(2).newTab(new_tab1.data);

    
    my_browser.mergeAllWindows();
    my_browser.print();
    my_browser.closeEmptyWindows();
    my_browser.print();*/

    /*tab my_tab1 = tab("10", "00", "00");
    tab my_tab2 = tab("20", "00", "00");
    tab my_tab3 = tab("30", "00", "00");
    tab my_tab4 = tab("40", "00", "00");
    tab my_tab5 = tab("50", "00", "00");
    tab my_tab6 = tab("60", "00", "00");
    tab my_tab7 = tab("70", "00", "00");*/
    // my_window.closeTab();
    // my_window.print();

    // my_window.newTab(my_tab1);
    // active_tab = my_window.getActiveTab();
    // my_window.newTab(my_tab2);
    // my_window.newTab(my_tab3);
    // my_window.newTab(my_tab4);
    // my_window.newTab(my_tab5);
    // my_window.newTab(my_tab6);
    // my_window.newTab(my_tab7);
    // my_window.closeTab();
    // my_window.print();
    // my_window.closeTab();
    // my_window.print();
    // my_window.closeTab();
    // my_window.print();
    // my_window.closeTab();
    // my_window.print();
    // my_window.closeTab();
    // my_window.print();
    // my_window.closeTab();
    // my_window.print();
    // my_window.closeTab();
    // my_window.print();
}

#endif // BROWSERPROJECT_MAIN_BROWSER_H
